/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PsywAzVmWeA
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Gallery() {
  return (
    <>
      <section className="w-full pt-12 md:pt-24 lg:pt-32">
        <div className="container grid gap-12 lg:grid-cols-[1fr_400px] lg:gap-24">
          <img
            alt="Featured Artwork"
            className="mx-auto aspect-[4/3] overflow-hidden rounded-xl object-cover object-center"
            height="600"
            src="/placeholder.svg"
            width="800"
          />
          <div className="space-y-6">
            <div className="space-y-2">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Ethereal Reflections</h1>
              <p className="text-gray-500 md:text-xl dark:text-gray-400">By Jane Doe</p>
            </div>
            <p className="text-gray-500 md:text-xl dark:text-gray-400">
              Immerse yourself in the captivating interplay of light and shadow, where the canvas becomes a window into
              a world of ethereal beauty. This striking artwork invites you to pause and reflect on the fleeting moments
              that shape our perception of reality.
            </p>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          <div className="group overflow-hidden rounded-lg">
            <Link className="block" href="#">
              <img
                alt="Artwork 1"
                className="aspect-[4/3] w-full overflow-hidden object-cover transition-all duration-300 group-hover:scale-105"
                height="300"
                src="/placeholder.svg"
                width="400"
              />
              <div className="p-4">
                <h3 className="text-lg font-semibold">Ethereal Reflections</h3>
                <p className="text-gray-500 dark:text-gray-400">Jane Doe</p>
              </div>
            </Link>
          </div>
          <div className="group overflow-hidden rounded-lg">
            <Link className="block" href="#">
              <img
                alt="Artwork 2"
                className="aspect-[4/3] w-full overflow-hidden object-cover transition-all duration-300 group-hover:scale-105"
                height="300"
                src="/placeholder.svg"
                width="400"
              />
              <div className="p-4">
                <h3 className="text-lg font-semibold">Chromatic Harmony</h3>
                <p className="text-gray-500 dark:text-gray-400">John Smith</p>
              </div>
            </Link>
          </div>
          <div className="group overflow-hidden rounded-lg">
            <Link className="block" href="#">
              <img
                alt="Artwork 3"
                className="aspect-[4/3] w-full overflow-hidden object-cover transition-all duration-300 group-hover:scale-105"
                height="300"
                src="/placeholder.svg"
                width="400"
              />
              <div className="p-4">
                <h3 className="text-lg font-semibold">Vibrant Expressions</h3>
                <p className="text-gray-500 dark:text-gray-400">Sarah Lee</p>
              </div>
            </Link>
          </div>
          <div className="group overflow-hidden rounded-lg">
            <Link className="block" href="#">
              <img
                alt="Artwork 4"
                className="aspect-[4/3] w-full overflow-hidden object-cover transition-all duration-300 group-hover:scale-105"
                height="300"
                src="/placeholder.svg"
                width="400"
              />
              <div className="p-4">
                <h3 className="text-lg font-semibold">Dreamscape Odyssey</h3>
                <p className="text-gray-500 dark:text-gray-400">Michael Chen</p>
              </div>
            </Link>
          </div>
          <div className="group overflow-hidden rounded-lg">
            <Link className="block" href="#">
              <img
                alt="Artwork 5"
                className="aspect-[4/3] w-full overflow-hidden object-cover transition-all duration-300 group-hover:scale-105"
                height="300"
                src="/placeholder.svg"
                width="400"
              />
              <div className="p-4">
                <h3 className="text-lg font-semibold">Celestial Whispers</h3>
                <p className="text-gray-500 dark:text-gray-400">Emily Park</p>
              </div>
            </Link>
          </div>
          <div className="group overflow-hidden rounded-lg">
            <Link className="block" href="#">
              <img
                alt="Artwork 6"
                className="aspect-[4/3] w-full overflow-hidden object-cover transition-all duration-300 group-hover:scale-105"
                height="300"
                src="/placeholder.svg"
                width="400"
              />
              <div className="p-4">
                <h3 className="text-lg font-semibold">Enigmatic Landscapes</h3>
                <p className="text-gray-500 dark:text-gray-400">David Lee</p>
              </div>
            </Link>
          </div>
          <div className="group overflow-hidden rounded-lg">
            <Link className="block" href="#">
              <img
                alt="Artwork 7"
                className="aspect-[4/3] w-full overflow-hidden object-cover transition-all duration-300 group-hover:scale-105"
                height="300"
                src="/placeholder.svg"
                width="400"
              />
              <div className="p-4">
                <h3 className="text-lg font-semibold">Ethereal Whispers</h3>
                <p className="text-gray-500 dark:text-gray-400">Jessica Kim</p>
              </div>
            </Link>
          </div>
          <div className="group overflow-hidden rounded-lg">
            <Link className="block" href="#">
              <img
                alt="Artwork 8"
                className="aspect-[4/3] w-full overflow-hidden object-cover transition-all duration-300 group-hover:scale-105"
                height="300"
                src="/placeholder.svg"
                width="400"
              />
              <div className="p-4">
                <h3 className="text-lg font-semibold">Chromatic Fusion</h3>
                <p className="text-gray-500 dark:text-gray-400">Alex Tan</p>
              </div>
            </Link>
          </div>
        </div>
      </section>
    </>
  )
}
