/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UQ8isCVfULe
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"

export function Glossary() {
  return (
    <main className="container mx-auto px-4 md:px-6 py-12 md:py-16">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl md:text-4xl font-bold mb-6">Glossary</h1>
        <div className="mb-8">
          <Input
            className="w-full rounded-md bg-gray-100 dark:bg-gray-800 px-4 py-2 text-gray-700 dark:text-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            placeholder="Search terms..."
            type="search"
          />
        </div>
        <div className="space-y-6">
          <div>
            <h2 className="text-xl md:text-2xl font-semibold mb-4">A</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="bg-gray-100 dark:bg-gray-800 rounded-md p-4">
                <h3 className="text-lg font-medium mb-2">Ability</h3>
                <p className="text-gray-700 dark:text-gray-300">
                  A special power or skill that a character can use in the game.
                </p>
              </div>
              <div className="bg-gray-100 dark:bg-gray-800 rounded-md p-4">
                <h3 className="text-lg font-medium mb-2">Aggro</h3>
                <p className="text-gray-700 dark:text-gray-300">
                  The act of drawing the attention or hostility of enemies in the game.
                </p>
              </div>
            </div>
          </div>
          <div>
            <h2 className="text-xl md:text-2xl font-semibold mb-4">B</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="bg-gray-100 dark:bg-gray-800 rounded-md p-4">
                <h3 className="text-lg font-medium mb-2">Boss</h3>
                <p className="text-gray-700 dark:text-gray-300">
                  A powerful enemy that the player must defeat to progress in the game.
                </p>
              </div>
              <div className="bg-gray-100 dark:bg-gray-800 rounded-md p-4">
                <h3 className="text-lg font-medium mb-2">Buff</h3>
                <p className="text-gray-700 dark:text-gray-300">
                  A temporary enhancement to a character's stats or abilities.
                </p>
              </div>
            </div>
          </div>
          <div>
            <h2 className="text-xl md:text-2xl font-semibold mb-4">C</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="bg-gray-100 dark:bg-gray-800 rounded-md p-4">
                <h3 className="text-lg font-medium mb-2">Cooldown</h3>
                <p className="text-gray-700 dark:text-gray-300">
                  The time a character must wait before using a certain ability again.
                </p>
              </div>
              <div className="bg-gray-100 dark:bg-gray-800 rounded-md p-4">
                <h3 className="text-lg font-medium mb-2">Crafting</h3>
                <p className="text-gray-700 dark:text-gray-300">
                  The process of creating items or equipment in the game.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}
